<a href="https://colab.research.google.com/github/anderalvarez/Computer-Vision/blob/main/Computer_Vision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [4]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
tensor_one_d = tf.constant([1,2,3,7,8,9])
print(tensor_one_d)

tf.Tensor([1 2 3 7 8 9], shape=(6,), dtype=int32)


In [9]:
tensor_two_d = tf.constant(
    [
      [1,2,3],
      [4,5,6],
      [7,8,9],
      [0,0,0]
    ]
)
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 0 0]], shape=(4, 3), dtype=int32)
