<a href="https://colab.research.google.com/github/anderalvarez/Computer-Vision/blob/main/Computer_Vision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- Tensors are Multi Dimensional Arrays
- An array is an ordered arrangement of numbers

In [2]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([1,2,3,7,8,9])
print(tensor_one_d)

tf.Tensor([1 2 3 7 8 9], shape=(6,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant(
    [
      [1,2,3],
      [4,5,6],
      [7,8,9],
      [0,0,0]
    ]
)
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 0 0]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant(
    [
        [[1,2,3],
        [4,5,6]]
        ,
        [[7,8,9],
        [0,0,0]]
        ,
        [[10,11,12],
        [12,11,10]]
        ,
        [[1,2,3],
        [4,5,6]]
    ]
)
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 0  0  0]]

 [[10 11 12]
  [12 11 10]]

 [[ 1  2  3]
  [ 4  5  6]]], shape=(4, 2, 3), dtype=int32)


Metodo Eye genera la matriz Identidad (Diagonal principal = 1, el resto 0)

In [6]:
eye_tensor = tf.eye(
    num_rows = 4,
    num_columns=None,
    batch_shape=[3,],
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape=(3, 4, 4), dtype=float32)


El metodo fill te crea una matriz rellenada con el dato que le indiques

In [8]:
tensor_filled = tf.fill(
    [2,3], 4, name=None, layout=None
)
print(tensor_filled)

tf.Tensor(
[[4 4 4]
 [4 4 4]], shape=(2, 3), dtype=int32)
